### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/coreupdater#25]
I am currently testing thirty bees - bleeding edge with PHP 8.1.
In Core Updater, I have following information:

![Zaznaczenie_211](https://user-images.githubusercontent.com/20421361/177936748-c876b027-2e5c-4c41-bdd0-2de4185c603d.png)

**Comment by getdatakick** [comment]
Fixed by introducing php8.1 build in tb core: thirtybees/thirtybees@32aa7d51cca6b685de0cb00da77794ce88629055
