### ISSUE TITLE
Core Updater should also update admin default theme

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/coreupdater#32]
I tried some changes to the tpl files and noticed that the module does not update those. I think this could be bundled together with the community themes switch as it has pretty much the same functionality.

**Comment by getdatakick** [comment]
Core updater already compares and updates admin theme tpl files. I've just tested this

![image](https://github.com/user-attachments/assets/18204b6e-8c26-4717-bc61-c1dce2560659)

**Comment by therampagerado** [comment]
Yes, of course. I messed up something yesterday. Sorry for wasting your time! :(
