### ISSUE TITLE
Unintentional configuration page

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/coreupdater#4]
See https://forum.thirtybees.com/topic/2936-spam-returns-with-url-in-last-name/?do=findComment&comment=27496

![](https://forum.thirtybees.com/uploads/monthly_2019_05/408995856_Screenshot_2019-05-14ModulesandServicesGquipment.png.3bbbfa42b8d3e1105da5499c21bb98da.png)

Intended text on the configuration page doesn't display. Looks like this is a multishop environment.

**Comment by Traumflug** [comment]
Can't reproduce it. Tried all settings I could imagine, even tried in the shop where the screenshot was taken (thanks for access, Peter!), no "dice".

If this happen again, please don't hesitate to re-open this issue.

**Comment by Traumflug** [comment]
Not yet solved, despite even more tries to reproduce this.

**Comment by Dh42** [comment]
Make sure you have multi-shop turned on and more than one shop set up. Then be in one shop context and install the module. It will take you to that page in the screenshot.

**Comment by Traumflug** [comment]
Yes, I did all this and have even access to back office of the shop where the above screenshot comes from. Doesn't happen to me, happens a minute later to the shop owner in the same shop installation.

**Comment by Traumflug** [comment]
Got it now, see f2d8a41f5c23f3dd46315ac05a925f1faf88fc2a. This will go into the next release.

Thanks again for reporting!
