### ISSUE TITLE
Core updater 1.2 does not let me compare db with TB 1.1.0

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/coreupdater#8]
![image](https://user-images.githubusercontent.com/11251370/63803210-08c6ed80-c91d-11e9-9795-47fc895aa625.png)

**Comment by therampagerado** [comment]
And coreupdater 1.2 is still not showing in backoffice as of now. Got referenced to the release by other commit of yours

**Comment by Traumflug** [comment]
There will be Core Updater v1.2.1 before too long, which will then appear in back office and work after updating core to v1.1.x or v1.1.1.

I hope this solves the question.
