### ISSUE TITLE
Coreupdater doesn't work with Windows

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/coreupdater#9]
Coreupdater doesn't work with Windows. You get an error like 
`ERROR: Failed to download files with error: fatal: path not found: \admin1/ajax-tab.php`

The problem is in the way the variable $adminDir is constructed in /modules/coreupdater/classes/GitUpdate.php:
`$adminDir = str_replace(_PS_ROOT_DIR_, '', _PS_ADMIN_DIR_);
 $adminDir = trim($adminDir, '/').'/';`

Both _PS_ROOT_DIR_ and _PS_ADMIN_DIR_ are dynamically constructed with php functions like realpath() and as such they contain backslashes under Windows. So under Windows the first line will put "\admin1" in the variable $adminDir and the trim() command on the next line won't have any effect.

I propose inserting 
`if($adminDir[0] == "\\") $adminDir = substr($adminDir,1);`
between the two lines at line 454 and 874. It will delete a leadingbackslash when present.

See also: https://forum.thirtybees.com/topic/2628-core-updater-windows-xampp-problem/

**Comment by ksimunovic** [comment]
@musicpanda seems to be already fixed a9abf97

**Comment by cjpgdk** [comment]
I think this should do the trick. for windows dir `\` escaping the `$adminDir` variable before parsing it to `preg_replace` .

I did this when upgrading, after this upgrade when without issues, and i were able to continue the development before releasing the shop update.

in [classes/GitUpdate.php#L881](https://github.com/thirtybees/coreupdater/blob/master/classes/GitUpdate.php#L881)

`$path = preg_replace('#^'.$adminDir.'#', 'admin/', $path);` 

to

`$path = preg_replace('#^'.preg_quote($adminDir).'#', 'admin/', $path);`

**Comment by Traumflug** [comment]
> $path = preg_replace('#^'.preg_quote($adminDir).'#', 'admin/', $path);

Good point. Picked to _master_, but applied out of the loop: 5d803340a95cb4405c9336636bc163c8e9f0cff5

As the other thing was picked as well, this issue should be solved.
